site_name: ReLAX (Reconstructed Lineage Analysis & eXploration)
docs_dir: docs
theme:
  name: material
  palette:
  - scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - scheme: slate
    primary: indigo
    accent: indigo
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
  features:
  - navigation.path
  - navigation.expand
  - content.code.annotate

plugins:
- search:
- mkdocstrings:
    handlers:
      python:
        options:
          show_submodules: true
          docstring_style: numpy

markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  # - pymdownx.extra
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true


nav:
  - Overview: index.md
  - Quick Start: ./quick_start/q_start.md
  - Napari Viewer: ./viewer/viewer.md
  - Explore and Relabel: ./explore_relabel/explore_relabel.md 
  - Attribute Recoloring: ./attribute/attribute.md
  - Distance Calculation:  ./distance/distance.md
  - Cross dataset Distances: 
    - Manager: ./cross+comparison/manager.md
    - Distance Calculation: ./cross+comparison/distance_cross.md
  - Guides: 
    - Index: ./guides/guides.md
    - Opening a dataset: ./guides/loading_data.md
    - Saving Progress: ./guides/saving/saving_tut.md
    - Hiding lineages: ./guides/show_and_hide/show_and_hide_tut.md
    - Comparing lineages: ./guides/comparing/blind_comparing.md
