site_name: ReLAX (Reconstructed Lineage Analysis & eXploration)
theme:
  name: material
  palette:
  - scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - scheme: slate
    primary: indigo
    accent: indigo
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
  features:
  - navigation.path
  - navigation.expand
  - content.code.annotate
  - content.tooltips
  - navigation.instant
  - navigation.sections
  - navigation.indexes
  - navigation.footer
  - toc.follow
  - search.suggest
  - search.share

plugins:
- search:
- mkdocstrings:
    handlers:
      python:
        options:
          show_submodules: true
          docstring_style: numpy

markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  # - pymdownx.extra
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true


nav:
  - Overview: index.md
  - Napari Viewer: viewer.md
  - Explore and Relabel: explore_relabel.md
  - Attribute Recoloring: attribute.md
  - Distance Calculation:  distance.md
  - Cross_dataset_Distances: 
    - Manager: manager.md
    - Distance Calculation: distance_cross.md
  - Guides: guides.md
