"""
This module contains four napari widgets declared in
different ways:

- a pure Python function flagged with `autogenerate: true`
    in the plugin manifest. Type annotations are used by
    magicgui to generate widgets for each parameter. Best
    suited for simple processing tasks - usually taking
    in and/or returning a layer.
- a `magic_factory` decorated function. The `magic_factory`
    decorator allows us to customize aspects of the resulting
    GUI, including the widgets associated with each parameter.
    Best used when you have a very simple processing task,
    but want some control over the autogenerated widgets. If you
    find yourself needing to define lots of nested functions to achieve
    your functionality, maybe look at the `Container` widget!
- a `magicgui.widgets.Container` subclass. This provides lots
    of flexibility and customization options while still supporting
    `magicgui` widgets and convenience methods for creating widgets
    from type annotations. If you want to customize your widgets and
    connect callbacks, this is the best widget option for you.
- a `QWidget` subclass. This provides maximal flexibility but requires
    full specification of widget layouts, callbacks, events, etc.

References:
- Widget specification: https://napari.org/stable/plugins/building_a_plugin/guides.html#widgets
- magicgui docs: https://pyapp-kit.github.io/magicgui/

Replace code below according to your needs.
"""

from typing import TYPE_CHECKING

from magicgui import widgets
from qtpy.QtWidgets import (
    QApplication,
    QComboBox,
    QStackedWidget,
    QVBoxLayout,
    QWidget,
)

from . import lineage_tree_analysis, relax_multipledatasets

if TYPE_CHECKING:
    pass


class ReLAXWidget(QWidget):
    """Abstract class for all the widgets"""

    # Module to parse (here None because it is the abstract class)
    module = None

    def __make_widget_combobox(self) -> QComboBox:
        """
        Function to generate a combo box of
        a list of widgets from a module
        """
        if self.module is None:
            return

        main_combobox = QComboBox()
        main_combobox._explicitly_hidden = False
        main_combobox.native = main_combobox

        main_stack = QStackedWidget()
        main_stack.native = main_stack
        self.widget_dictionary = {}

        for im_info_class in self.module.__all_widgets__:
            w_created = im_info_class(self.viewer)
            main_combobox.addItem(w_created.name)
            main_stack.addWidget(w_created)
            self.widget_dictionary[w_created.name] = w_created

        main_combobox.currentIndexChanged.connect(main_stack.setCurrentIndex)
        main_combobox.name = "main_combobox"
        main_stack.name = "main_stack"

        main_control = widgets.Container(
            widgets=[
                main_combobox,
                main_stack,
            ],
            labels=False,
        )
        return main_control

    def __init__(self, napari_viewer):
        super().__init__()
        self.viewer = napari_viewer
        main_control = self.__make_widget_combobox()
        layout = QVBoxLayout()
        layout.setSpacing(0)
        self.setLayout(layout)
        self.layout().addWidget(main_control.native)
        if self.module.__overall_widget__:
            self.layout().addWidget(
                self.module.__overall_widget__(self.viewer)
            )
        screen = QApplication.primaryScreen()
        dpi = screen.logicalDotsPerInch()
        scale = dpi / 96
        font = self.font()
        font.setPointSizeF(font.pointSizeF() * scale)
        self.setFont(font)
        layout.addStretch(1)


class LineageTreeAnalysisWidget(ReLAXWidget):
    module = lineage_tree_analysis  # for the time being

    def __init__(self, napari_viewer):
        super().__init__(napari_viewer)
        explore_and_relabel = self.widget_dictionary["Explore and Relabel"]
        explore_and_relabel.w_lineedit.returnPressed.connect(
            self.widget_dictionary["Distance Calculation"].config.label_update
        )
        explore_and_relabel.w_lineedit.returnPressed.connect(
            self.widget_dictionary[
                "Distance Calculation"
            ].clustermap.receive_new_labels
        )
        self.widget_dictionary[
            "Attribute Based Recoloring"
        ].coloring_widget.quant.color_signal.connect(
            explore_and_relabel.canvas.change_attributes
        )
        
        # Also update the lineage color box when colors change
        self.widget_dictionary[
            "Attribute Based Recoloring"
        ].coloring_widget.quant.color_signal.connect(
            self.widget_dictionary[
                "Explore and Relabel"
            ].update_lineage_color_box
        )


class CrossEmbryoComparisonWidget(ReLAXWidget):
    module = relax_multipledatasets

    def __init__(self, napari_viewer):
        super().__init__(napari_viewer)
        self.widget_dictionary[
            "Manager Manipulation"
        ].send_manager_to_classes.connect(
            self.widget_dictionary["Cross Distance Calculation"].get_lt_manager
        )
